[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_swirl_v0 = "8vqgdewQChSQVdnBcYCUftq5RGKFjoandbzMFPJ3n69u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/gabrielrojas/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
